import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner/Banner";
import NavBar from "../components/NavBar/NavBar";
import SectionCards from "../components/Card/Section-Cards";
import {
  getVideos,
  getPopularVideos,
  getPreviouslyWatchedVideos,
} from "../lib/videos";
import useRedirectUser from "../utils/redirectUser";

export async function getServerSideProps(context: any) {
  const { userId, cookiesToken } = await useRedirectUser(context);
  if (!userId) {
    return {
      props: {},
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  const token = cookiesToken;
  const watchedVideos = await getPreviouslyWatchedVideos(token, userId);

  const actionVideos = await getVideos("New Action Movie Trailers");
  const horrorVideos = await getVideos("New Horror Trailers");
  const dramaVideos = await getVideos("New Drama Trailers");
  const comedyVideos = await getVideos("New Comedy Trailers");

  const popularVideos = await getPopularVideos();
  return {
    props: {
      actionVideos,
      horrorVideos,
      dramaVideos,
      comedyVideos,
      popularVideos,
      watchedVideos,
    },
  };
}

export default function Home(props: any) {
  const {
    actionVideos,
    horrorVideos,
    dramaVideos,
    comedyVideos,
    popularVideos,
    watchedVideos,
  } = props;
  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavBar username="ml60379@umbc.edu" />

        <Banner
          videoId="WHXxVmeGQUc"
          title="The Irishman"
          subTitle="In the 1950s, truck driver Frank Sheeran gets involved with Russell Bufalino and his Pennsylvania crime family. As Sheeran climbs the ranks to become a top hit man, he also goes to work for Jimmy Hoffa -- a powerful Teamster tied to organized crime."
          imgUrl="/static/IrishmanImage.jpg"
          titleImgUrl="/static/IrishmanTitleCard.png"
        />

        <div className={styles.sectionWrapper}>
          <SectionCards title="Action" videos={actionVideos} size="large" />
          <SectionCards
            title="Watch Again"
            videos={watchedVideos}
            size="small"
          />
          <SectionCards title="Horror" videos={horrorVideos} size="medium" />
          <SectionCards title="Comedy" videos={dramaVideos} size="small" />
          <SectionCards title="Drama" videos={comedyVideos} size="medium" />
          <SectionCards
            title="Popular Videos"
            videos={popularVideos}
            size="small"
          />
        </div>
      </main>
    </>
  );
}
